import Loading from '@/components/startbucks/loading';
import Nav from '@/components/startbucks/nav';
import { RouteChangeListener } from '@/components/startbucks/rotute-change-listener';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import { soDoFont } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={soDoFont.className}>
      <body className="flex flex-col leading selection:bg-seagreen relative">
        <Suspense fallback={<Loading />}>
          <RouteChangeListener />
          <Nav />
          <main>{children}</main>
        </Suspense>
      </body>
    </html>
  );
}
